# Generated by Django 5.1.7 on 2025-04-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='created_at',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='salary',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
