# Generated by Django 5.1.7 on 2025-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_rename_created_at_jobpost_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('Estágio', 'Estágio'), ('Freelancer', 'Freelancer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
