# Generated by Django 5.1.7 on 2025-03-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('Candidato', 'Candidato'), ('Recrutador', 'Recrutador')], default='Candidato', max_length=10)),
                ('senha', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
            ],
        ),
    ]
